# Generated by Django 2.2.3 on 2019-07-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetmodal',
            options={'ordering': ['-pk']},
        ),
    ]
